// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMzQq-9KGxSudWPgw9yaddEFOfVk9rZ4A',
    appId: '1:843820917894:web:c673e78a9a19ebb6505d07',
    messagingSenderId: '843820917894',
    projectId: 'apicall-7c90c',
    authDomain: 'apicall-7c90c.firebaseapp.com',
    storageBucket: 'apicall-7c90c.appspot.com',
    measurementId: 'G-MYPSBH9XE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xwGvf7-VpZGSUJ4Du0bLpQHvSR7AUGc',
    appId: '1:843820917894:android:149ea27f68d26b02505d07',
    messagingSenderId: '843820917894',
    projectId: 'apicall-7c90c',
    storageBucket: 'apicall-7c90c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhwF-tk-mTb6hTa7EFo9xBQYtnnxZ-1M0',
    appId: '1:843820917894:ios:e9257899e209d99a505d07',
    messagingSenderId: '843820917894',
    projectId: 'apicall-7c90c',
    storageBucket: 'apicall-7c90c.appspot.com',
    iosClientId: '843820917894-s22acbr4812n813ntafksf2jhdck6ons.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhwF-tk-mTb6hTa7EFo9xBQYtnnxZ-1M0',
    appId: '1:843820917894:ios:f718482796e9bfbf505d07',
    messagingSenderId: '843820917894',
    projectId: 'apicall-7c90c',
    storageBucket: 'apicall-7c90c.appspot.com',
    iosClientId: '843820917894-4uc1nvrr94ijoidn6engbnedhko19it6.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickOrder.RunnerTests',
  );
}
